version: '3.7'

services:
  db_service:
    image: mongo:4.2.5-bionic
    container_name: db_service
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  api_service:
    build:
      context: ../..
      dockerfile: ./bin/local/Dockerfile
    image: node:13
    container_name: api_service
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "3000:3000"
    volumes:
      - ../..:/opt/api_service
      - ../../node_modules:/opt/api_service/node_modules
    networks:
      - app-network
    command:
      - '/opt/api_service/bin/local/service_start.sh'
    links:
      - db_service

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
