version: '3.7'

services:
  db-server:
    container_name: db-server
    image: mongo:4.2.5-bionic
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  api-server:
    container_name: api-server
    build:
      context: ../..
      dockerfile: ./bin/local/Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - '../..:/opt/api_server/'
      - '../../package.json:/opt/api_server/package.json'
      - '../../node_modules:/opt/api_server/node_modules'
    command:
      - './bin/local/service_start.sh'
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "3000:3000"
    networks:
      - app-network
    links:
      - db-server

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
