image: asia.gcr.io/turtleopedia/turtleopedia:latest

variables:
  DEV_STAGE_NAME: dev
  PROD_STAGE_NAME: prod
  STAGING_STAGE_NAME: staging
  SERVER_CI_REGISTRY_IMAGE: asia.gcr.io/turtleopedia/turtleopedia
  GCR_REGION_URL: https://asia.gcr.io

stages:
  - build
  - test
  - package
  - deploy

# For manual triggering Step
.manual_step: &manual_step
  when: manual
  allow_failure: false

include:
  - local: '/deployments/gitlab-ci-configs/server.yml'
