image: registry.gitlab.com/skynetaps/skynet

variables:
  DEV_STAGE_NAME: dev
  PROD_STAGE_NAME: prod
  STAGING_STAGE_NAME: staging

stages:
  - build
  - test
  - package
  - deploy

# For manual triggering Step
.manual_step: &manual_step
  when: manual
  allow_failure: false

include:
  - local: '/deployments/gitlab-ci-configs/server.yml'
