# Build Step
.build_alpha: &build_alpha
  stage: build
  image: node:13
  script: source deployments/scripts/client_alpha_build.sh
  artifacts:
    paths:
      - client/alpha/dist/
      - client/alpha/node_modules/

build_alpha:prod:
  extends: .build_alpha
  environment:
    name: prod
  only:
    - /^alpha-v[0-9]*\.[0-9]*\.[0-9]*$/

# Lint Step
.lint_alpha: &lint_alpha
  stage: test
  image: node:13
  script: source deployments/scripts/client_alpha_lint.sh
  artifacts:
    paths:
      - client/alpha/dist/

lint_alpha:prod:
  extends: .lint_alpha
  dependencies:
    - build_alpha:prod
  environment:
    name: prod
  only:
    - /^alpha-v[0-9]*\.[0-9]*\.[0-9]*$/

.deploy_alpha: &deploy_alpha
  stage: deploy
  image: python:latest
  script: source deployments/scripts/client_alpha_deploy.sh

deploy_alpha:prod:
  extends: .deploy_alpha
  variables:
    AWS_ACCESS_KEY_ID: ${PROD_AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${PROD_AWS_SECRET_KEY}
    DEPLOYMENT_BUCKET: ${PROD_ALPHA_DEPLOYMENT_BUCKET}
    CFN_DISTRIBUTION_ID: ${PROD_ALPHA_CFN_DISTRIBUTION_ID}
  only:
    - /^alpha-v[0-9]*\.[0-9]*\.[0-9]*$/
  dependencies:
    - lint_alpha:prod
  environment:
    name: prod
    url: https://admin.turtleopedia.com
