## Build Step
#.build_delta: &build_delta
#  stage: build
#  image: node:13
#  script: source deployments/scripts/client_delta_build.sh
#  artifacts:
#    paths:
#      - client/delta/dist/
#      - client/delta/node_modules/
#
#build_delta:prod:
#  extends: .build_delta
#  environment:
#    name: prod
#  only:
#    - /^delta-v[0-9]*\.[0-9]*\.[0-9]*$/

# Lint Step
.lint_delta: &lint_delta
  stage: test
  image: node:13
  script: source deployments/scripts/client_delta_lint.sh
  artifacts:
    paths:
      - client/delta/dist/

lint_delta:prod:
  extends: .lint_delta
  dependencies:
    - build_delta:prod
  environment:
    name: prod
  only:
    - /^delta-v[0-9]*\.[0-9]*\.[0-9]*$/

.deploy_delta: &deploy_delta
  stage: deploy
  image: node:10
  script: source deployments/scripts/client_delta_deploy.sh

deploy_delta:prod:
  extends: .deploy_delta
  variables:
    AWS_REGION: ${PROD_AWS_REGION}
  only:
    - /^delta-v[0-9]*\.[0-9]*\.[0-9]*$/
  before_script:
    - npm install -g @angular/cli
  dependencies:
    - lint_delta:prod
  environment:
    name: prod
    url: https://www.turtleopedia.com
