# Sitemap Step -- this required build step
.sitemap_delta: &sitemap_delta
  stage: sitemap
  image: node:13
  script: source deployments/scripts/client_delta_sitemap.sh
  artifacts:
    paths:
      - client/delta/src

sitemap_delta:prod:
  extends: .sitemap_delta
  variables:
    NODE_ENV: production
    BASE_URL: https://www.turtleopedia.com
    MONGO_URL_SUBSTRING: mongodb+srv://turtleopedia:ET6qUjmbJnnxRrtF@turtleopedia-production-ba3gv.gcp.mongodb.net
    MONGO_DB_DELTA: delta
  only:
    - master
    - /^delta-v[0-9]*\.[0-9]*\.[0-9]*$/

# Build Step
.build_delta: &build_delta
  stage: build
  image: node:13
  script: source deployments/scripts/client_delta_build.sh
  artifacts:
    paths:
      - client/delta/dist/
      - client/delta/node_modules/

build_delta:prod:
  extends: .build_delta
  dependencies:
    - sitemap_delta:prod
  environment:
    name: prod
  only:
    - /^delta-v[0-9]*\.[0-9]*\.[0-9]*$/

# Lint Step
.lint_delta: &lint_delta
  stage: test
  image: node:13
  script: source deployments/scripts/client_delta_lint.sh
  artifacts:
    paths:
      - client/delta/dist/
      - client/delta/node_modules

lint_delta:prod:
  extends: .lint_delta
  dependencies:
    - build_delta:prod
  environment:
    name: prod
  only:
    - /^delta-v[0-9]*\.[0-9]*\.[0-9]*$/

.deploy_delta: &deploy_delta
  stage: deploy
  image: node:13
  script: source deployments/scripts/client_delta_deploy.sh

deploy_delta:prod:
  extends: .deploy_delta
  variables:
    FIREBASE_DEPLOY_KEY: ${FIREBASE_TOKEN}
    FIREBASE_CI_PROJECT: ${FIREBASE_CI_PROJECT}
  only:
    - /^delta-v[0-9]*\.[0-9]*\.[0-9]*$/
  dependencies:
    - lint_delta:prod
  environment:
    name: prod
    url: https://www.turtleopedia.com
