build_server:
  stage: build
  image: node:13
  only:
    - master
  script: source deployments/scripts/server_build.sh
  artifacts:
    paths:
      - server/node_modules/

test_server:
  stage: test
  image: node:13
  only:
    - master
  dependencies:
    - build_server
  services:
    - mongo:latest
  variables:
    MONGO_INITDB_ROOT_USERNAME: ballu
    MONGO_INITDB_ROOT_PASSWORD: skynetballu123

  script: source deployments/scripts/server_test.sh

lint_server:
  stage: test
  image: node:13
  only:
    - master
  dependencies:
    - build_server

  script: source deployments/scripts/server_lint.sh

.package_server:
  image: docker:git
  stage: package
  services:
    - docker:dind
  variables:
    CI_REGISTRY_IMAGE: ${SERVER_CI_REGISTRY_IMAGE}
    CI_ENVIRONMENT_SLUG: prod
    DOCKER_IMAGE_TAG: 'gcr.io/turtleopedia/turtleopedia'
  script: source deployments/scripts/server_package.sh

package_server:staging:
  extends: .package_server
  only:
    - master
    - dev
  environment:
    name: prod
    url: http://turtleopedia.com

.deploy_server: &deploy_server
  stage: deploy
  services:
    - docker:dind

deploy_server:staging:
  extends: .deploy_server
  image: docker:git
  services:
    - docker:dind
  only:
    - master
    - dev
  environment:
    name: prod
    url: https://$HEROKU_APP_NAME.herokuapp.com
  dependencies:
    - package_server:staging
  before_script:
    - docker login -u ${GCP_SERVICE_KEY} --password-stdin https://gcr.io
  script:
    - source deployments/scripts/server_deploy_gcp.sh
