build_server:
  stage: build
  image: node:13
  script: source deployments/scripts/server_build.sh
  only:
    - dev
    - master
    - merge_requests
    - /^api-v[0-9]*\.[0-9]*\.[0-9]*$/
  artifacts:
    paths:
      - server/node_modules/

test_server:
  stage: test
  image: node:13
  dependencies:
    - build_server
  services:
    - mongo:latest
  variables:
    MONGO_INITDB_ROOT_USERNAME: ballu
    MONGO_INITDB_ROOT_PASSWORD: skynetballu123
  script: source deployments/scripts/server_test.sh
  only:
    - dev
    - master
    - merge_requests
    - /^api-v[0-9]*\.[0-9]*\.[0-9]*$/

lint_server:
  stage: test
  image: node:13
  dependencies:
    - build_server
  script: source deployments/scripts/server_lint.sh
  only:
    - dev
    - master
    - merge_requests
    - /^api-v[0-9]*\.[0-9]*\.[0-9]*$/


.package_server:
  image: docker:git
  stage: package
  services:
    - docker:dind
  script: source deployments/scripts/server_package.sh

package_server:production:
  extends: .package_server
  only:
    - /^api-v[0-9]*\.[0-9]*\.[0-9]*$/
  variables:
    CI_REGISTRY_IMAGE: ${SERVER_CI_REGISTRY_IMAGE}
    CI_ENVIRONMENT_SLUG: prod
    GCR_URL: ${GCR_REGION_URL}
  environment:
    name: prod
    url: http://api.turtleopedia.com


.deploy_server: &deploy_server
  stage: deploy
  services:
    - docker:dind
  script:
    - source deployments/scripts/server_deploy_gcp.sh

deploy_server:production:
  extends: .deploy_server
  image: google/cloud-sdk:latest
  services:
    - docker:dind
  only:
    - /^api-v[0-9]*\.[0-9]*\.[0-9]*$/
  environment:
    name: prod
  dependencies:
    - package_server:production
  variables:
    CI_REGISTRY_IMAGE: ${SERVER_CI_REGISTRY_IMAGE}
    CI_ENVIRONMENT_SLUG: prod
