const BCRYPT_HASH_ROUNDS = 10;
const PHONE_REGEX = /^\+[0-9]{1,4}[0-9]{10}$/;
const BLOG_POST_CATEGORIES = ['technology', 'lifestyle', 'entertainment'];
const DELTA_POSTS_PAGINATED_URL = 'http://delta/posts?';

module.exports = {
  PHONE_REGEX: PHONE_REGEX,
  BCRYPT_HASH_ROUNDS: BCRYPT_HASH_ROUNDS,
  BLOG_POST_CATEGORIES: BLOG_POST_CATEGORIES,
  DELTA_POSTS_PAGINATED_URL: DELTA_POSTS_PAGINATED_URL,
};
