apiVersion: v1
data:
  ALPHA_JWT_SECRET_KEY: ALPHA_JWT_SECRET_KEY_2
  BALLU_JWT_SECRET_KEY: BALLU_JWT_SECRET_KEY
  DELTA_JWT_SECRET_KEY: DELTA_JWT_SECRET_KEY
  JWT_SECRET_KEY: JWT_SECRET_KEY
  MONGO_DB_DELTA: MONGO_DB_DELTA
  MONGO_DB_HELIUM: MONGO_DB_HELIUM
  MONGO_URL_SUBSTRING: mongodb+srv://turtleopedia-production-ba3gv.gcp.mongodb.net
  NODE_ENV: production
  PORT: "3000"
  MONGO_DB: delta

kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-07T18:04:35Z"
  labels:
    app: turtleopedia-production
  name: turtleopedia-production-config-61cb
  namespace: turtleopedia-production
  resourceVersion: "38658"
  selfLink: /api/v1/namespaces/turtleopedia-production/configmaps/turtleopedia-production-config-61cb
  uid: 587a2b65-a8e9-11ea-a07f-42010aa00091
