apiVersion: v1
data:
  BASE_URL: https://api.turtleopedia.com
  GCLOUD_PROJECT: my-turtleopedia
  GCS_BUCKET: turtleopedia_assets_prod
  GCS_KEYFILE: keyfile.json
  MONGO_DB_DELTA: delta
  MONGO_URL_SUBSTRING: mongodb+srv://turtleopedia:ET6qUjmbJnnxRrtF@turtleopedia-production-ba3gv.gcp.mongodb.net
  NODE_ENV: production
  PORT: "3000"
  TURTLEOPEDIA_JWT_SECRET_KEY: TURTLEOPEDIA_JWT_SECRET_KEY
kind: ConfigMap
metadata:
  labels:
    app: api-service
  name: api-service-config-g4ky
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/api-service-config-g4ky
